title: BrenoAV
description: Personal website
baseurl: "" # for user.github.io root
url: "https://brenoav.github.io"

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: "highlight"

theme: null
plugins: []
